apiVersion: v1
name: alertmanager
description: alertmanager chart that runs on kubernetes
version: 1.0.14
keywords:
  - alertmanager
  - kubernetes
home: https://github.com/stakater-charts/alertmanager
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
