alertmanager:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.14.0
  image:
    tag: v0.14.0
  replicas: 3
  externalUrl: http://127.0.0.1:9093
  nodeSelector:
    key: failure-domain.beta.kubernetes.io/zone
    value: us-west-2a
  alertmanagerMain: main
  # resources:
  #   requests:
  #     memory: 200Mi
  #     cpu: 200m
  #   limits:
  #     memory: 400Mi
  #     cpu: 400m
  service:
    annotations:
      config.xposer.stakater.com/Domain: stackator.com
      config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
      config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Namespace}}.{{.Domain}}'
      config.xposer.stakater.com/TLS: "true"
      xposer.stakater.com/annotations: |-
        kubernetes.io/ingress.class: internal-ingress
        ingress.kubernetes.io/force-ssl-redirect: true
        certmanager.k8s.io/cluster-issuer: letsencrypt-production
    expose: "true"
  secrets:
    alertManagerConfig: ""
