alertmanager:
  tolerations: {}
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.14.0
  image:
    tag: v0.14.0
  replicas: 3
  externalUrl: http://127.0.0.1:9093
  nodeSelector: {}
  alertmanagerMain: main
  # resources:
  #   requests:
  #     memory: 200Mi
  #     cpu: 200m
  #   limits:
  #     memory: 400Mi
  #     cpu: 400m
  service:
    annotations: {}
    expose: "true"
  secrets:
    alertManagerConfig: ""
