apiVersion: v1
kind: Secret
metadata:
  name: {{ template "alertmanager.name" . }}-main
  labels:
{{ include "alertmanager.labels.stakater" . | indent 4 }}
{{ include "alertmanager.labels.chart" . | indent 4 }}
data:
  alertmanager.yaml: {{ .Values.alertmanager.secrets.alertManagerConfig | b64enc }}
