apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "alertmanager.labels.stakater" . | indent 4 }}
{{ include "alertmanager.labels.chart" . | indent 4 }}
    expose: "{{ .Values.alertmanager.service.expose }}"
    alertmanager: {{ .Values.alertmanager.alertmanagerMain }}
  name: {{ template "alertmanager.name" . }}-main
{{- if .Values.alertmanager.service.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: main
